import './assets/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";
import Header from "@/components/layout/Header";
import {getDictionary} from "@/dictionaries/dictionaries";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
                                             children, params,
                                         }: {
    children: React.ReactNode,
    params: { lang: string },
}) {

    const dictionary: Promise<any> = await getDictionary(params.lang);
    console.log('language ' + params.lang);
    console.log(dictionary);

    return (
        <html lang={params.lang || 'ca'}>
        <body className={inter.className}>
        <Header lang={params.lang} />
        <div className="container mx-auto">
            <main className="text-foreground bg-background">
                {children}
            </main>
        </div>
        </body>
        </html>
    )
}
